services:
  postgres:
    image: postgres:15

    container_name: etl_warehouse

    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_secret

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: